### ISSUE TITLE
Mensaje en S.A.M.E.

### ISSUE THREAD

**Issue by sabas1080** [manuel-rabade/sismo_alerta#6]
Hola, excelente trabajo 
¿tendrás entre tus curiosidades uno(s) mensaje(s) completo(s) de SAME que me puedas pasar?

-CIV-RWT-000000+0300-1311432-XGDF/003-D&@...

saludos y gracias

**Comment by manuel-rabade** [comment]
Hola,

Antes que nada muchas gracias por las felicitaciones y de verdad una disculpa por la demora.

Te comparto por acá http://ftp.rabade.net/tmp/sismo_alerta_logs-20150127-20150825.tar.gz los registros de operación del 26 de Enero al 28 de Agosto de la versión monitor de Sismo Alerta. En ellos puedes ver los mensajes SAME en crudo además de otras cosas como los reportes de calidad de recepción.

También por otra parte puedes dar click en los enlaces que acompañan a las publicaciones de https://twitter.com/sismoalertamx para ver los mensaje SAME en texto plano.

Saludos!
