### ISSUE TITLE
¿Aún se encuentra activo el proyecto?

### ISSUE THREAD

**Issue by dsalcedo** [manuel-rabade/sismo_alerta#7]

**Comment by pixelead0** [comment]
Hola @dsalcedo al parecer el proyecto es funcional, al menos que sugieras alguna mejora.

**Comment by manuel-rabade** [comment]
Mi última contribución al repo fue hace 2 años así que activo no lo llamaría. Por otra parte el proyecto sigue siendo vigente mientras se transmita la señal de la alerta sísmica en la banda de Weather Radio (NWR) mediante el protocolo SAME.
